/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/models/model.glb -o src/components/ModelGLTF.tsx --types 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    antique_katana_01: THREE.Mesh
  }
  materials: {
    antique_katana_01: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/model.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.antique_katana_01.geometry} material={materials.antique_katana_01} />
    </group>
  )
}

useGLTF.preload('/models/model.glb')
